#1: Started integration test.
exasol/exasol-java-tutorial pull request #2
Opened 2021-10-25 10:12 UTC by redcatbear

Closes #1.

2021-10-25 14:21 UTC, kaklakariada requested changes

2021-10-25 14:21 UTC, kaklakariada commented on README.md
> +Start your journey with the obligatory [hello world](doc/tutorial/hello_world-md) tutorial to learn the basics of defining an inline Java extension that can be called from SQL.
```suggestion
Start your journey with the obligatory [hello world](doc/tutorial/hello_world.md) tutorial to learn the basics of defining an inline Java extension that can be called from SQL.
```

2021-10-25 14:21 UTC, kaklakariada commented on README.md
> +
Maybe add some general info: what will you learn? And what is a Java extension for Exasol?

2021-10-25 14:21 UTC, kaklakariada commented on doc/changes/changes_0.1.0.md
> +Code name:
Code name missing

2021-10-25 14:21 UTC, kaklakariada commented on doc/changes/changes_0.1.0.md
> +* ISSUE_NUMBER: description
Issue number missing

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/hello_world.md
> +The absolute simplest possible extension that you can write in Java, is a [function script](https://docs.exasol.com/database_concepts/udf_scripts/java.htm).
What is a function script? I could follow the link, but a short sentence would make it clear immediately.

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/hello_world.md
> +Once you installed this extension, you can call it like any other scalar function:
How do I install it? There are no instructions ;)

Please also add instructions how to connect to the docker-db (host, port, credentials).

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/hello_world.md
> +```
What is the expected output?

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +To separate content from layout the articles are written in Markdown and rendered via Cascading Stylesheets (CSS).
```suggestion
You work as a data scientist at a big online tech-magazine. The people in your company publish about a hundred news articles and how-tos on your blog per year.
To separate content from layout the articles are written in Markdown and rendered via Cascading Stylesheets (CSS).
```

What is the convention for Markdown: hard wraps or no hard wraps?

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +docker run --name exasoldb -p 127.0.0.1:8563:8563 --detach --privileged --stop-timeout 120  exasol/docker-db:7.1.2
```suggestion
docker run --name exasoldb --publish 127.0.0.1:8563:8563 --detach --privileged --stop-timeout 120  exasol/docker-db:7.1.2
```

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/hello_world.md
> +docker run --name exasoldb -p 127.0.0.1:8563:8563 --detach --privileged --stop-timeout 120  exasol/docker-db:7.1.2
```suggestion
docker run --name exasoldb --publish 127.0.0.1:8563:8563 --detach --privileged --stop-timeout 120  exasol/docker-db:7.1.2
```

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/hello_world.md
> +docker run --name exasoldb -p 127.0.0.1:8563:8563 --detach --privileged --stop-timeout 120  exasol/docker-db:7.1.2
Add a note that the data will be lost when stopping the container.

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +docker run --name exasoldb -p 127.0.0.1:8563:8563 --detach --privileged --stop-timeout 120  exasol/docker-db:7.1.2
Add a note that the data will be lost when stopping the container.

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +1. [`test-db-builder-java`](https://github.com/exasol/test-db-builder-java): quickly create test database structures and contents
```suggestion
1. [`test-db-builder-java`](https://github.com/exasol/test-db-builder-java): quickly create test database structures and contents
1. [`hamcrest-resultset-matcher`](https://github.com/exasol/hamcrest-resultset-matcher): check the results of JDBC queries against expectations
```

Reorder. You first need test data, then you can verify the result

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +...
```suggestion
// ...
```
❓

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +Be careful with clean test setup though when using this option. While the Exasol testcontainer cleans up the database with the start of each new test class, it does not do this for each individual te
```suggestion
Be careful with clean test setup though when using this option. While the Exasol testcontainer cleans up the database content with the start of each new test class, it does not do this for each individual test case. If you want to avoid problems, either make sure your tests create resources that don't interfere with each other or purge the database in `beforeEach()`.
```
❓

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +Next we set up the [`test-db-builder-java`](https://github.com/exasol/test-db-builder-java). This allows us to create database structures an populate them with data in a compact and readable fashion.
```suggestion
Next we set up the [`test-db-builder-java`](https://github.com/exasol/test-db-builder-java). This allows us to create database structures and populate them with data in a compact and readable fashion.
```

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +...
```suggestion
// ...
```

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +If you haven't heard of [hamcrest matchers](http://hamcrest.org/), then now is the perfect time to take a break from this tutorial here and [read up on this very useful matcher framework](http://hamc
```suggestion
Last but not least, we also import the [`hamcrest-resultset-matcher`](https://github.com/exasol/hamcrest-resultset-matcher), that let's us compare the JDBC result sets our test runs yield with our expectations. If you haven't heard of [hamcrest matchers](http://hamcrest.org/), then now is the perfect time to take a break from this tutorial here and [read up on this very useful matcher framework](http://hamcrest.org/JavaHamcrest/tutorial).
```

Hard wraps in markdown?

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +The first import gives us an enum value that we will later use to switch of type matching in a test where the Java type is irrelevant because we are only interested in the value.
```suggestion
The first import gives us an enum value that we will later use to switch off type matching in a test where the Java type is irrelevant because we are only interested in the value.
```

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +Finally, we have the import of the actual result set matcher.
Is it necessary to explain every import? I think it's enough to just see how it's used.

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +Finally we hold the result against our expectation with are seven words, one heading and one paragraph.
```suggestion
Finally we hold the result against our expectation which are seven words, one heading and one paragraph.
```

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +Finally we hold the result against our expectation with are seven words, one heading and one paragraph.
These are magic numbers in the test case. Could we also assert the column names? Then the meaning of these numbers would be clear.

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +The most complicated part is abstracted by the method `installMdStatsScript()`.
```suggestion
The most complicated part is abstracted by the method `installMdStatsScript()`:
```

❓

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +...
```suggestion
// ...
```

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +    ...
```suggestion
    // ...
```

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +    private void installMdStatsScript() throws AssertionError {
```suggestion
    private void installMdStatsScript() {
```

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +    private void installMdStatsScript() throws AssertionError {
```suggestion
    private void installMdStatsScript() {
```

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +Note here that we inject the class name, the path in the bucket and the file name in the SQL, to avoid coupling.
Now we should run the tests, please add instructions for the `mvn` call. Also add a note that the initial start will take some minutes for downloading & startup of the db.

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +## Building an Integration Test
I am missing the actual implementation. Please first describe the implementation.
Also instructions for manual deployment and testing might be interesting, because the actual goal is deployment to production, not integration tests.

2021-10-25 14:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +
As a reader I would be interested in how to deploy the final product, i.e. how to build (`mvn package`?) and install the jar.

Are there any recommendations how to automate deployment to test / production environments?

2021-10-25 14:21 UTC, kaklakariada commented on pom.xml
> +            <version>6.1.7</version>
Is this the latest version?

2021-10-25 14:21 UTC, kaklakariada commented on src/main/java/com/exasol/javatutorial/markdown/ElementCountVisitor.java
> +    private int paragraph;
```suggestion
    private int paragraphCount = 0;
```
❓

2021-10-25 14:21 UTC, kaklakariada commented on src/main/java/com/exasol/javatutorial/markdown/ElementCountVisitor.java
> +        }
This looks a bit complicated. Could you also split the text using a regexp and count the result?

2021-10-25 14:21 UTC, kaklakariada commented on src/main/java/com/exasol/javatutorial/markdown/MdStat.java
> +    @SuppressWarnings({ "java:S112", "java:S1172" })
Please add justification for suppressing the warnings.

2021-10-25 14:21 UTC, kaklakariada commented on src/main/java/com/exasol/javatutorial/markdown/MdStat.java
> +        final MarkdownStatisticsScanner scanner = new MarkdownStatisticsScanner();
This creates a new scanner for every row. Would it be more efficient to keep this in a static constant?

2021-10-25 14:21 UTC, kaklakariada commented on src/test/java/com/exasol/javatutorial/markdown/MarkdownStatisticsScalarScriptIT.java
> +            MarkdownStatisticsScalarScriptIT.connection.close();
```suggestion
        if (connection != null) {
            connection.close();
```
Or is this by intention?

2021-10-25 14:21 UTC, kaklakariada commented on src/test/resources/ssl.crt
> +-----BEGIN CERTIFICATE-----
Is this file here by intention?

2021-10-27 06:56 UTC, redcatbear commented on README.md
> +
Added.

2021-10-27 07:03 UTC, redcatbear commented on README.md
> +Start your journey with the obligatory [hello world](doc/tutorial/hello_world-md) tutorial to learn the basics of defining an inline Java extension that can be called from SQL.
Fixed.

2021-10-27 07:08 UTC, redcatbear commented on doc/changes/changes_0.1.0.md
> +Code name:
Added.

2021-10-27 07:08 UTC, redcatbear commented on doc/changes/changes_0.1.0.md
> +* ISSUE_NUMBER: description
Added.

2021-10-27 07:10 UTC, redcatbear commented on doc/tutorial/mdstats.md
> +If you haven't heard of [hamcrest matchers](http://hamcrest.org/), then now is the perfect time to take a break from this tutorial here and [read up on this very useful matcher framework](http://hamc
Makes the paragraphs more readable.

2021-10-27 07:29 UTC, redcatbear commented on doc/tutorial/hello_world.md
> +The absolute simplest possible extension that you can write in Java, is a [function script](https://docs.exasol.com/database_concepts/udf_scripts/java.htm).
Added.

2021-10-27 08:23 UTC, redcatbear commented on doc/tutorial/hello_world.md
> +Once you installed this extension, you can call it like any other scalar function:
Added. And a lot more.

2021-10-27 09:29 UTC, redcatbear commented on doc/tutorial/mdstats.md
> +Note here that we inject the class name, the path in the bucket and the file name in the SQL, to avoid coupling.
Added.

2021-10-27 13:10 UTC, redcatbear commented on doc/tutorial/mdstats.md
> +
Added.

2021-10-27 13:13 UTC, redcatbear commented on pom.xml
> +            <version>6.1.7</version>
Yes, according to: https://maven.exasol.com/artifactory/exasol-releases/com/exasol/exasol-script-api/

2021-10-27 13:14 UTC, redcatbear commented on src/main/java/com/exasol/javatutorial/markdown/ElementCountVisitor.java
> +        }
I could, but I wanted to demonstrate a fast option.

2021-10-27 13:20 UTC, redcatbear commented on src/main/java/com/exasol/javatutorial/markdown/MdStat.java
> +        final MarkdownStatisticsScanner scanner = new MarkdownStatisticsScanner();
Done.

2021-10-27 13:56 UTC, redcatbear commented on src/test/resources/ssl.crt
> +-----BEGIN CERTIFICATE-----
C&P error from the test resources of `exasol-testcontainers`.
Removed.

2021-10-27 16:06 UTC, kaklakariada commented on src/main/java/com/exasol/javatutorial/markdown/ElementCountVisitor.java
> +        }
Good argument!

2021-10-29 12:21 UTC, kaklakariada requested changes

2021-10-29 12:21 UTC, kaklakariada commented on README.md
> +If you are a Java developer and you are thinking about extending Exasol with new functionality, this tutorial takes you tour around Exasol's interfaces and the libraries we provide.
```suggestion
If you are a Java developer and you are thinking about extending Exasol with new functionality, this tutorial takes you on a tour around Exasol's interfaces and the libraries we provide.
```

2021-10-29 12:21 UTC, kaklakariada commented on README.md
> +* Scalar Script UDF (a script with a single input)
```suggestion
* Scalar Script UDF (a script with a single input and output)
```
❓

2021-10-29 12:21 UTC, kaklakariada commented on doc/changes/changes_0.1.0.md
> +# Exasol Java tutorial 0.1.0, released 2021-10-27
```suggestion
# Exasol Java tutorial 0.1.0, released 2021-10-29
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/changes/changes_0.1.0.md
> +The other one builds on the first an introduces a scalar script that emits three columns. The main focus of that tutorial is not on the implementation though but on how to create an automated integra
```suggestion
The other one builds on the first and introduces a scalar script that emits three columns. The main focus of that tutorial is not on the implementation though but on how to create an automated integration test that verifies the UDF you wrote.
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/hello_world.md
> +We forward two ports from the docker instance to the host here, the standard database port 8563 and the [BucketFS](https://docs.exasol.com/administration/on-premise/bucketfs/bucketfs.htm) port 2580.
👍

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/hello_world.md
> +Since we are not defining the entry class name via a special directive, we need to make sure that the class name and the script name are identical. That is why the class is called `HELLO`, which brea
```suggestion
Since we are not defining the entry class name via a special directive, we need to make sure that the class name and the script name are identical. That is why the class is called `HELLO`, which breaks the established naming conventions in Java which says that class names should be upper camel case.
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/hello_world.md
> +While you could call the scalar function `"Hello"` (including the double quotes, we do not recommend this, since it is an established standard in SQL to use the databases default case for function na
```suggestion
While you could call the scalar function `"Hello"` (including the double quotes), we do not recommend this, since it is an established standard in SQL to use the databases default case for function names. Since Exasol's default case is upper case, the name `HELLO` is the best choice.
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/hello_world.md
> +If you look at the classes implementation, you will find it trivial. Think of the `run` method like a Java applications typical main method. It has a fixed signature that you need to adhere to if you
```suggestion
If you look at the classes implementation, you will find it trivial. Think of the `run` method like a Java application's typical main method. It has a fixed signature that you need to adhere to if you want Exasol to find the entry point of the script.
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/hello_world.md
> +`ExaMetadata metadata` holds a lot of the information about the script and the environment it runs in. The `ExaIterator context` provides functions for scanning the input values and emmiting complex
```suggestion
The `run` method's parameter `ExaMetadata metadata` holds a lot of the information about the script and the environment it runs in. The `ExaIterator context` parameter provides functions for scanning the input values and emitting complex output. Neither are used in this example, so we are going to accept their existence and otherwise ignore them for now.
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/hello_world.md
> +Congratulations, you successfully created an ran your first own Exasol extension in Java.
```suggestion
Congratulations, you successfully created and ran your first own Exasol extension in Java 🎉 
```
;)

2021-10-29 12:21 UTC, kaklakariada commented on src/main/java/com/exasol/javatutorial/markdown/MdStat.java
> +    // Unused parameters and throwing of class Exception required to match entry method signature.
👍

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +If you are unsure which client to pick, use [curl](https://curl.se/)
```suggestion
If you are unsure which client to pick, use [curl](https://curl.se/).
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +You will understand the main principle if look at this snippet:
```suggestion
You will understand the main principle if you look at this snippet:
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +What you see here is a call-back function that the tree walker call every time it hits a heading. Counting is then simple enough, we just keep a counter in an instance variable. Needless to say that
```suggestion
What you see here is a call-back function that the tree walker calls every time it hits a heading. Counting is then simple enough, we just keep a counter in an instance variable. Needless to say that this class is intended to be disposed after each scan. Since we are doing only a single scan, nothing bad can happen.
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +Counting paragraphs is equally simple. There is a little bit more work involved for counting the words. We won't go into details here, since that is besides the point of this tutorial. You can always
```suggestion
Counting paragraphs is equally simple. There is a little bit more work involved for counting the words. We won't go into details here, since that is besides the point of this tutorial. You can always read the code if you are curious.
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +Here we are first creating a parser. We do this as an instance variable, so that if `scan` was called multiple times, we would safe the effort of doing that repeatedly.
```suggestion
Here we are first creating a parser. We do this as an instance variable, so that if `scan` was called multiple times, we would save the effort of doing that repeatedly.
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +Inside the `scan` method, we let the Markdown scanner scan the Markdown document, then we inject our own visitor into the tree walker of the document and fire it up using `accept`.
```suggestion
Inside the `scan` method, we let the Markdown parser parse the Markdown document, then we inject our own visitor into the tree walker of the document and fire it up using `accept`.
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +As a result our visitor how has all the statistics and we can return them.
```suggestion
As a result our visitor now has all the statistics and we can return them.
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +That's it where the implementation is concerned. Not too complicated, is it?
```suggestion
That's it what the implementation is concerned. Not too complicated, is it?
```
❓

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +Now that we have all the parts of the implementation place, we still need to deploy our extension. Unlike in our "hello world" example inlining the Java code into SQL code is not an option anymore. F
```suggestion
Now that we have all the parts of the implementation in place, we still need to deploy our extension. Unlike in our "hello world" example inlining the Java code into SQL code is not an option anymore. First we have an external dependency that is packaged as a JAR and thus impossible to inline, second the attempt to inline even this mildly complex Java code would get unmaintainable as SQL / Java hybrid code in a single script. Third and by no means last, demonstrating how to deploy and test a properly packaged Java plug-in is the whole point of this tutorial.
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +This is perfectly possible and there are situations where this absolutely makes sense. If the license of the external dependency for example requires that you distribute it in unmodified form. Or if
```suggestion
This is perfectly possible and there are situations where this absolutely makes sense, e.g. if the license of the external dependency for example requires that you distribute it in unmodified form. Or if you want your users to be able to update your part and the external dependency independently, e.g. if the library is a driver. In that case updating the driver might be necessary in order to keep your plugin compatible with newer versions of the service the driver attaches to. We take that approach in our [Virtual Schemas](https://github.com/exasol/virtual-schemas).
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +On the other hand, it is more convenient for users if they need to install only a single artifact as a plugin. Fewer moving parts means fewer places where things can go wrong. In this case you should
```suggestion
On the other hand, it is more convenient for users if they need to install only a single artifact as a plugin. Fewer moving parts means fewer places where things can go wrong. In this case you should build an all-in-one JAR or as the folk saying goes a "fat JAR".
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +Please take a look a the file `../../pom.xml` again. In the `plugins` section there is one entry using the `maven-assembly-plugin` that tells Maven to build everything into a single JAR archive &mdas
```suggestion
Please take a look a the file `[pom.xml](../../pom.xml)` again. In the `plugins` section there is one entry using the `maven-assembly-plugin` that tells Maven to build everything into a single JAR archive &mdash; including all dependencies.

If you are not using Maven, you will easily find instructions how to build fat JARs with your tool.
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +When it comes to naming, note that in this example we sacrificed an important aspect of artifact naming for the sake of simplicity. The artifact name does not contain a version number, which for a pr
❓ 
```suggestion
When it comes to naming, note that in this example we sacrificed an important aspect of artifact naming for the sake of simplicity. The artifact name does not contain a version number, which for a production plug-in is **absolutely a should feature**! We did this so that the documentation and the test code remain stable across versions of this tutorial. In a real-world scenario we highly recommend that you include the version number in the JAR name! You can use the Maven variable `project.version` to achieve this:
```

2021-10-29 12:21 UTC, kaklakariada commented on doc/tutorial/mdstats.md
> +
Please add a short note how to run the function, e.g. `SELECT MDSTAT('# Markdown\n\nExample')` and what the result should look like.

A more realistic example would be to create and fill a table and run MDSTAT on that table.

2021-10-29 12:26 UTC, redcatbear commented on README.md
> +* Scalar Script UDF (a script with a single input)
Not quite, since it emits three columns.

2021-10-29 12:31 UTC, kaklakariada submitted a review, later dismissed

2021-10-29 12:36 UTC, redcatbear commented on doc/tutorial/mdstats.md
> +When it comes to naming, note that in this example we sacrificed an important aspect of artifact naming for the sake of simplicity. The artifact name does not contain a version number, which for a pr
"feature" is a verb here.

2021-10-29 12:55 UTC, kaklakariada submitted a review, later dismissed

2021-11-02 12:14 UTC, kaklakariada approved these changes

2021-11-02 12:31 UTC, merged