#28: Explain relationship between host authentication and server certificate
exasol/exasol-java-tutorial pull request #32
Opened 2023-08-30 11:11 UTC by redcatbear

Closes #28.

2023-08-30 13:04 UTC, kaklakariada requested changes

2023-08-30 13:04 UTC, kaklakariada commented on tls-tutorial/doc/use_your_own_certificate.md
> +If you have a host that is intended to be reachable under multiple hostnames, please read about the concept of the "Subject Alternative Name" (see [RFC5280, 4.2.1.6](https://www.rfc-editor.org/rfc/rf
```suggestion
If you have a host that is intended to be reachable under multiple hostnames, please read about the concept of the "Subject Alternative Name" (SAN, see [RFC5280, 4.2.1.6](https://www.rfc-editor.org/rfc/rfc5280.html#page-35)). SAN is outside the scope of this tutorial. 
```

2023-08-30 13:04 UTC, kaklakariada commented on tls-tutorial/doc/use_your_own_certificate.md
> +    CERT_HOSTNAME='<fully-qualified-hostname>'
```suggestion
    CERT_HOSTNAME='host.example.com'
```

2023-08-30 13:04 UTC, kaklakariada requested changes
Also add changelog entry

2023-08-31 06:06 UTC, redcatbear commented
Done.

2023-08-31 06:27 UTC, kaklakariada approved these changes

2023-08-31 06:31 UTC, merged