#42: Testing tutorial: TDD
exasol/exasol-java-tutorial pull request #45
Opened 2023-11-13 15:20 UTC by redcatbear

Related #42.

2023-11-14 11:15 UTC, kaklakariada requested changes

2023-11-14 11:15 UTC, kaklakariada commented on .github/workflows/ci-build.yml
Mark as generated

2023-11-14 11:15 UTC, kaklakariada commented on .github/workflows/release_droid_prepare_original_checksum.yml
Mark this as generated

2023-11-14 11:15 UTC, kaklakariada commented on .github/workflows/release_droid_print_quick_checksum.yml
Mark this as generated

2023-11-14 11:15 UTC, kaklakariada commented on .github/workflows/release_droid_upload_github_release_assets.yml
Mark this as generated

2023-11-14 11:15 UTC, kaklakariada commented on .project-keeper.yml
>    - "LICENSE-exasol-script-api.txt|https://mit-license.org/"
Is this still required?

2023-11-14 11:15 UTC, kaklakariada commented on .settings/org.eclipse.jdt.core.prefs
Mark this as generated

2023-11-14 11:15 UTC, kaklakariada commented on doc/changes/changes_0.2.0.md
Version 0.2.0 was already released. Revert changes to this file.

2023-11-14 11:15 UTC, kaklakariada commented on markdown-statistics-tutorial/pom.xml
> +                <version>2.9.12</version>
```suggestion
                <version>2.9.16</version>
```

2023-11-14 11:15 UTC, kaklakariada commented on pom.xml
> +                <version>2.9.12</version>
```suggestion
                <version>2.9.16</version>
```

2023-11-14 11:15 UTC, kaklakariada commented on testing-tutorial/.settings/org.eclipse.jdt.core.prefs
Mark this as generated

2023-11-14 11:15 UTC, kaklakariada commented on testing-tutorial/.settings/org.eclipse.jdt.ui.prefs
Mark this as generated

2023-11-14 11:15 UTC, kaklakariada commented on tls-tutorial/pom.xml
> +                <version>2.9.12</version>
```suggestion
                <version>2.9.16</version>
```

2023-11-14 13:35 UTC, kaklakariada requested changes
General:
* Add links to `README.md`
* Add a table of contents for the Testing Tutorial
* Add links to previous/next file and/or add a number to each of the .md files
* New tests are not executed when running `mvn test`
* Maybe mention mutation testing

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/introduction.md
> +3. Tests are an executable form or specification &mdash; if you can't formulate a test, your specification has holes
```suggestion
1. Developers make mistakes, tests help uncovering them
2. Tests help avoiding regressions
3. Tests are an executable form of specification &mdash; if you can't formulate a test, your specification has holes
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/introduction.md
> +On 4 June 1996 the first Ariane 5 launcher veer of course and self-destructed due to a software bug [[LIONS1996]](#lions1996).
```suggestion
On 4 June 1996 the first Ariane 5 launcher veered off course and self-destructed due to a software bug [[LIONS1996]](#lions1996).
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/introduction.md
> +It was a on overflow in a conversion from a 64-bit floating point number to a 16-bit integer that caused both Inertial Reference Systems (SRI) to enter and report a failure state. The root cause was
```suggestion
It was a on overflow in a conversion from a 64-bit floating point number to a 16-bit integer that caused both Inertial Reference Systems (SRI) to enter and report a failure state. The root cause was a combination of reusing software from a previous launch vehicle on the newer Ariane 5 model and a downward conversion that did not fail safely in case of overflow. The overflow itself was due considerably higher horizontal velocity of Ariane 5 compared to its predecessor. Since the On-Board Computer (OBC) misinterpreted the error bit pattern as an actual measurement, engaged in drastic course correction causing the solid state thrusters to break loose due to mechanical stress. This in turn triggered self-destruction of the launcher.
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/automatic_testing.md
> +This only adds to the mental burden that eas away at your productivity. Task switches take time, and they cost our brain a lot of energy.
```suggestion
This only adds to the mental burden that eats away at your productivity. Task switches take time, and they cost our brain a lot of energy.
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/automatic_testing.md
> +1. &hellip; very fast
```suggestion
1. &hellip; are very fast
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/software_testing.md
> +> The exmaple throughout the document
```suggestion
> The example throughout the document
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/software_testing.md
Add a note to this file that these are just notes.

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/software_testing.md
> +## Automatic vs. Manual
```suggestion
## Automatic vs. Manual  ✅
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/multiple_asserts_in_one_test_case.md
> +Wrapping the assertions in a list of lambdas inside `assert_all` makes sure the test case runs all of them regardless of whether they succeed.
```suggestion
Wrapping the assertions in a list of lambdas inside `assertAll()` makes sure the test case runs all of them regardless of whether they succeed.
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/multiple_asserts_in_one_test_case.md
> +A classical example of this situation is when you have to validate exceptions.
Good example!

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/multiple_asserts_in_one_test_case.md
> +It is pretty obvious that checking the exception message requires that an exception is caught first. There is no point here in using `assertAll`.
```suggestion
It is pretty obvious that checking the exception message requires that an exception is caught first. There is no point here in using `assertAll()`.
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/multiple_asserts_in_one_test_case.md
> +The good news is that this is usually a rare case.
Add a section "Expensive Setup". If the test setup is expensive you want to run as many assertions as possible to avoid re-running the test.

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/first_steps_into_tdd.md
> +We highly recommend you follow the example with a modern IDE like [IntelliJ](https://www.jetbrains.com/idea/) or [Eclipse](https://www.eclipse.org/).
... or VSCode :-P

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/first_steps_into_tdd.md
> +1. Create an empty Maven project called `projectmanagement` in your IDE.
Should we explain how to do this for Eclipse/IntelliJ? Or let the users find out themselves ;)
Will this also add JUnit & Hamcrest dependencies?

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/first_steps_into_tdd.md
> +2. There is a significant chance that simply fixing the compiler findings will get the test green _before_ you actually wrote the implementation. This is a classical example of a dangerous test. And
Maybe put this paragraph into a "Note" box

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/first_steps_into_tdd.md
> +    }
Strictly following TDD, shouldn't you add a second test and keep the original? Of course this would mean adding a default project name.

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/first_steps_into_tdd.md
> +![One test succeeds, one fails](images/screenshot_failing_test_with_mutated_values.png)
Good example!

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/first_steps_into_tdd.md
> +Let's work on the role next. We want a role to consist of zero or more permissions. Since permissions are a finite, countable entity, we are simply using an enum here with the required two entries. O
You could however add tests for
* number of permissions
* conversion to string (i.e. permission name)
* ...

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/first_steps_into_tdd.md
> +So if the test is OK, why it is still green before we implemented anything? Well, it's because we actually implemented something. Especially with boolean functions you can see that a seemingly harmle
Good point!

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/red_green_clean.md
> +Please assign the constructor vararg parameter to an instance variable `permissions` of type `List<String> permissions`. And use a `contains` check in `hasPermission`.
```suggestion
Please convert the constructor vararg parameter from `Permission[]` to `List<Permission>` and assign it to an instance variable `permissions`. And use a `contains()` check in `hasPermission()`.
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/red_green_clean.md
> +private final List<Permission> permissions;
```suggestion
    private final List<Permission> permissions;
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/red_green_clean.md
> +    }
This test is not in the Java class. Maybe add it additionally there for references

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/red_green_clean.md
> +Let's go back to our role and permission example. With only permissions two you have four permutations in the role and the code is more expressive when spelled out. If you have ten different permissi
```suggestion
Let's go back to our role and permission example. With only tow permissions you have four permutations in the role and the code is more expressive when spelled out. If you have ten different permissions, you have 1024 permutations, and it is pretty clear that spelling them all out is neither efficient nor useful.
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/red_green_clean.md
> +If you apply this, you get a small set of tests for `toString`.
```suggestion
If you apply this, you get a small set of tests for `toString()`.
```
Shouldn't we implement `toString()` also TDD, i.e. add a test, then the implementation? This adds three tests at once.

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/red_green_clean.md
> +| Are they meaningful?                | ✅       | Thanks to limiting ourselves to boundary cases each of them adds value.                             |
```suggestion
| Criteria                            | Applies | Details                                                                                             |
|-------------------------------------|---------|-----------------------------------------------------------------------------------------------------|
| Did we avoid all duplication?       | ❌      | There is still a small amount of duplication. The pattern repeats.                                  |
| Do we avoid coupling between tests? | ✅      | Each tests a distinct aspect. Setup is separate. Changing one test does not affect the others.      |
| Are the tests descriptive?          | ✅      | They have proper names that will show up in the test log. The tests themselves are trivial to read. |
| Are they meaningful?                | ✅      | Thanks to limiting ourselves to boundary cases each of them adds value.                             |
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/red_green_clean.md
> +    static void testSomeAspect() {
```suggestion

    @Test
    static void testSomeAspect() {
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/red_green_clean.md
> +                ()-> assertThat(resultset.size = 7)
This is not working Java code ;)

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/red_green_clean.md
> +                .grant(table,SELECT,UDPATE);
```suggestion
    @Test
    void testImportShopItems() {
        final Table table = schema.createTable("ITEMS", "PRODUCT_ID", "DECIMAL(18,0)", "NAME", "VARCHAR(40)")
                .insert("1", "Cat food")
                .insert("2", "Toy mouse");
        final User user = factory.createUser("KIMIKO")
                .grant(CREATE_SESSION)
                .grant(table, SELECT, UDPATE);
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/red_green_clean.md
> +    }
```suggestion
    static void beforeAll() {
        factory = new ExasolObjectFactory(connection);
    }
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/red_green_clean_fast.md
> +> There is no doubt that the grail of efficiency leads to abuse. Programmers waste enormous amounts of time thinking about, or worrying about, the speed of noncritical parts of their programs, and th
```suggestion
> There is no doubt that the grail of efficiency leads to abuse. Programmers waste enormous amounts of time thinking about, or worrying about, the speed of noncritical parts of their programs, and these attempts at efficiency actually have a strong negative impact when debugging and maintenance are considered. We should forget about small efficiencies, say about 97% of the time: pre-mature optimization is the root of all evil.
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/red_green_clean_fast.md
> +> Yet we should not pass up our opportunities in that critical 3%. A good programmer will not be lulled into complacency by such reasoning, he will be wise to look carefully at the critical code; but
```suggestion
> Yet we should not pass up our opportunities in that critical 3%. A good programmer will not be lulled into complacency by such reasoning, he will be wise to look carefully at the critical code; but only after that code has been identified.
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/doc/tdd/red_green_clean_fast.md
> +Testing code is not production code. While [we want tests to be fast](../automatic_testing.md#speed-matters), we should focus on testing the correct thing. Performance optimization tends to make test
```suggestion
Testing code is not production code. While [we want tests to be fast](../automatic_testing.md#speed-matters), we should focus on testing the correct thing. Performance optimization tends to make tests more complex, which in turn makes them harder to read and in the end harder to determine if they are correct.
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/model/test_cycle_in_an_ideal_world.plantuml
> +@startuml
This is not used in Markdown. Maybe delete it.

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/pom.xml
> +                <version>2.9.12</version>
```suggestion
                <version>2.9.16</version>
```

2023-11-14 13:35 UTC, kaklakariada commented on testing-tutorial/src/main/java/com/exasol/javatutorial/projectmanagement/Role.java
> +        this.permissions = Set.of(permissions);
The tutorial said this was a `List` ;)

2023-11-14 15:05 UTC, kaklakariada requested changes

2023-11-14 15:05 UTC, kaklakariada commented on testing-tutorial/doc/dealing_with_randomness.md
> +No. If the users need ordering, they can sort on the target database. The import process should not care about ordering. First of all ordering is inherently expensive, second if the import can cope w
```suggestion
No. If the users need ordering, they can sort on the target database. The import process should not care about ordering. First of all ordering is inherently expensive, second if the import can cope with any order, that makes parallel import possible.
```

2023-11-14 15:05 UTC, kaklakariada commented on testing-tutorial/doc/dealing_with_randomness.md
> +The lazy approach is to throw in the odd `sleep` and hope for the best. This is a recipe for unreliable tests, since there is nothing that guarantees that just because your wait was long enough when
```suggestion
The lazy approach is to throw in the odd `sleep` and hope for the best. This is a recipe for unreliable tests and wasting time, since there is nothing that guarantees that just because your wait was long enough when you wrote the test and executed it once, it will be long enough at any given other time.
```

2023-11-14 15:05 UTC, kaklakariada commented on testing-tutorial/doc/tdd/tdd_and_bdd.md
> +2. The design will be cleaner TDD fosters separating concerns better, in order to test units in isolation
```suggestion
2. The design will be cleaner because TDD fosters separating concerns better, in order to test units in isolation
```

2023-11-14 15:05 UTC, kaklakariada commented on testing-tutorial/doc/tdd/tdd_and_bdd.md
> +3. The solution will be less complex, since you only implement what is needed to make the tests succeed
```suggestion
3. The solution will be less complex and better maintainable, since you only implement what is needed to make the tests succeed
```

2023-11-14 15:07 UTC, kaklakariada requested changes

2023-11-14 15:07 UTC, kaklakariada commented on testing-tutorial/doc/tdd/first_steps_into_tdd.md
> +If you haven't done so already, please also familiarize yourself with [Apache Maven](https://maven.apache.org/) and [Hamcrest matchers](../matchers/hamcrest_matchers.md). We will use both throughout
The "Hamcrest matchers" is broken.

2023-11-15 07:22 UTC, redcatbear commented on .github/workflows/release_droid_print_quick_checksum.yml
Added.

2023-11-15 08:14 UTC, redcatbear commented on .project-keeper.yml
>    - "LICENSE-exasol-script-api.txt|https://mit-license.org/"
Upgraded to UDF API Java 1.0.3 and removed replacement.

2023-11-15 08:17 UTC, redcatbear commented on doc/changes/changes_0.2.0.md
Added.

2023-11-15 08:42 UTC, redcatbear commented on testing-tutorial/doc/tdd/first_steps_into_tdd.md
> +1. Create an empty Maven project called `projectmanagement` in your IDE.
Mentioned adding the dependencies. I don't think we need a full how-to-use-your-IDE here.

2023-11-15 08:54 UTC, redcatbear commented on testing-tutorial/doc/tdd/first_steps_into_tdd.md
> +2. There is a significant chance that simply fixing the compiler findings will get the test green _before_ you actually wrote the implementation. This is a classical example of a dangerous test. And
As discussed, we don't put this in an extra box.

2023-11-15 14:57 UTC, kaklakariada requested changes

2023-11-15 14:57 UTC, kaklakariada commented on .gitattributes
> +.settings/org.eclipse.core.resources.prefs                       linguist-generated=true
```suggestion
```
This should be ignored

2023-11-15 14:57 UTC, kaklakariada commented on .gitattributes
> +.settings/org.eclipse.m2e.core.prefs                             linguist-generated=true
```suggestion
```
should also be ignored

2023-11-15 14:57 UTC, kaklakariada commented on .gitattributes
Some files are now duplicated here ;)

2023-11-15 14:57 UTC, kaklakariada commented on .project-keeper.yml
> -  - "LICENSE-exasol-script-api.txt|https://mit-license.org/"
:+1:

2023-11-15 14:57 UTC, kaklakariada commented on testing-tutorial/doc/multiple_asserts_in_one_test_case.md
> +The closer to the user a test is the more expensive it gets in terms of runtime. It is not uncommon for say an end-to-end test to be so expensive that you will want to avoid repeating the test setup.
:+1:

2023-11-15 14:57 UTC, kaklakariada commented on testing-tutorial/doc/tdd/red_green_clean.md
> +                .toArray(Permission[]::new);
:+1:

2023-11-15 14:57 UTC, kaklakariada commented on testing-tutorial/doc/tdd/red_green_clean.md
> +                ()-> assertThat(resultset.size, equalTo(7))
```suggestion
                ()-> assertThat(resultset.size(), equalTo(7))
```

2023-11-21 08:10 UTC, redcatbear commented on .gitattributes
> +.settings/org.eclipse.core.resources.prefs                       linguist-generated=true
Added to .gitignore and removed file.

2023-11-21 13:41 UTC, kaklakariada submitted a review, later dismissed

2023-11-22 05:19 UTC, kaklakariada submitted a review, later dismissed

2023-11-22 07:00 UTC, kaklakariada approved these changes

2023-11-22 07:08 UTC, merged